### PR TITLE
Changes to battery levels, based on official app.

### LINKED ISSUE #13: Incorrect Low Battery Warning
After a several day long power outage, the Homebridge plugin reports 0% battery, but the official app has it at about 2/3. I’ll try to do more troubleshooting tomorrow after work. I’m also not quite sure why it shows that it is charging in this plugin.

16F307DC-019D-4691-9FE0-6D57FED527F1
D7DDE120-B976-43C8-B8BE-BC82B8E7A743

### PR DESCRIPTION
**Pull request by Sunoo**
Fixes #13 

I just changed min and max voltage based on the code from the Android app. I used `t` of 6 for max and 5 for min, since those seemed to be the most reasonable choices based on their code (full above 5.9, dead below 5), but I'm open to tweaks if you think other values are more appropriate.

### CODE REVIEW

**Comment by Sunoo** [comment]
Actually, was the 29100 something you recorded? Maybe I shouldn't have changed that one. That'd be t=6.4 in their code, which seems plausible, since that would be 0.5 above their previous step, with the next two steps being 0.4 and 0.5. Perhaps the better range would be t=6.4 down to t=4.6 or so?

**Comment by dgreif** [comment]
I honestly can't remember if that max was from my fresh batteries or a calculation. I'd probably focus more on the minimum at this point

**Comment by Sunoo** [comment]
Okay, now I am actually going to bed though, so I'll revert the change to max in the morning.

**Comment by Sunoo** [comment]
Okay, updated to leave maxVoltage as it was.

**Pull request merged**
